const {Telegraf,Markup}=require('telegraf');
const db=require('../database/db');
const env=require('../config/env');
const {translateText,detectLanguage}=require('./services/translation');
const {getOrCreateGroup,updateGroup}=require('./services/group-settings');
const {createEnquiry}=require('./services/notifications');

function buildBot(){
 if(!env.botToken)return null;
 const bot=new Telegraf(env.botToken);
 const isGroup=ctx=>['group','supergroup'].includes(ctx.chat?.type);
 async function isAdmin(ctx){if(!isGroup(ctx))return false;try{const m=await ctx.telegram.getChatMember(ctx.chat.id,ctx.from.id);return ['creator','administrator'].includes(m.status)}catch{return false}}
 const customerMenu=()=>Markup.inlineKeyboard([[Markup.button.webApp('🏠 Open Maline Apartments',env.webAppUrl)],[Markup.button.callback('📅 Schedule Viewing','customer:viewing'),Markup.button.callback('💬 Message Staff','customer:message')],[Markup.button.callback('🌐 Language Help','customer:languages')]]);
 bot.start(ctx=>ctx.reply('🏢 Welcome to Maline Apartments V4.1\n\nBrowse rooms, save favorites, schedule a viewing, book an apartment, or contact our team.',customerMenu()));
 bot.command('help',ctx=>ctx.reply(['/start — customer menu','/settings — group configuration','/setlanguages en zh — choose two group languages','/setmode primary|ignore — messages in other languages','/translation_on /translation_off','/welcome_on /welcome_off','/setwelcome Your welcome text','/setstaff — use this group for staff notifications','/reply REFERENCE Your message — reply to a customer'].join('\n')));
 bot.command('settings',ctx=>{if(!isGroup(ctx))return ctx.reply('Use this command inside a group.');const g=getOrCreateGroup(ctx.chat);return ctx.reply(`⚙️ ${g.title}\n\nTranslation: ${g.translation_enabled?'ON':'OFF'}\nLanguages: ${g.primary_language} ↔ ${g.secondary_language}\nOther languages: ${g.other_language_mode}\nWelcome: ${g.welcome_enabled?'ON':'OFF'}\nCustom welcome: ${g.welcome_message?'Yes':'No'}`)});
 bot.command('setlanguages',async ctx=>{if(!(await isAdmin(ctx)))return ctx.reply('Only group administrators can change languages.');const a=ctx.message.text.trim().split(/\s+/).slice(1);if(a.length!==2)return ctx.reply('Usage: /setlanguages en zh');getOrCreateGroup(ctx.chat);updateGroup(ctx.chat.id,{primary_language:a[0].toLowerCase(),secondary_language:a[1].toLowerCase()});return ctx.reply(`✅ Translation pair: ${a[0]} ↔ ${a[1]}`)});
 bot.command('setmode',async ctx=>{if(!(await isAdmin(ctx)))return ctx.reply('Admins only.');const mode=ctx.message.text.trim().split(/\s+/)[1];if(!['primary','ignore'].includes(mode))return ctx.reply('Usage: /setmode primary or /setmode ignore');getOrCreateGroup(ctx.chat);updateGroup(ctx.chat.id,{other_language_mode:mode});return ctx.reply(`✅ Other-language mode: ${mode}`)});
 for(const [cmd,field,value,label] of [['translation_on','translation_enabled',1,'Translation enabled'],['translation_off','translation_enabled',0,'Translation disabled'],['welcome_on','welcome_enabled',1,'Welcome enabled'],['welcome_off','welcome_enabled',0,'Welcome disabled']])bot.command(cmd,async ctx=>{if(!(await isAdmin(ctx)))return ctx.reply('Admins only.');getOrCreateGroup(ctx.chat);updateGroup(ctx.chat.id,{[field]:value});return ctx.reply(`✅ ${label}`)});
 bot.command('setwelcome',async ctx=>{if(!(await isAdmin(ctx)))return ctx.reply('Admins only.');const text=ctx.message.text.replace(/^\/setwelcome(@\w+)?\s*/,'').trim();if(!text)return ctx.reply('Usage: /setwelcome Welcome {first_name} to {group_name}');getOrCreateGroup(ctx.chat);updateGroup(ctx.chat.id,{welcome_message:text});return ctx.reply('✅ Welcome message updated.')});
 bot.command('setstaff',async ctx=>{if(!(await isAdmin(ctx)))return ctx.reply('Admins only.');getOrCreateGroup(ctx.chat);updateGroup(ctx.chat.id,{staff_group_id:String(ctx.chat.id)});db.prepare(`INSERT INTO app_settings(key,value) VALUES('staff_group_id',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value`).run(String(ctx.chat.id));return ctx.reply('✅ This is now the main Maline staff notification group.')});
 bot.command('reply',async ctx=>{if(!(await isAdmin(ctx)))return ctx.reply('Staff administrators only.');const parts=ctx.message.text.split(/\s+/);const ref=parts[1];const message=parts.slice(2).join(' ').trim();if(!ref||!message)return ctx.reply('Usage: /reply ENQ-REFERENCE Your reply');const e=db.prepare('SELECT * FROM enquiries WHERE reference=?').get(ref);if(!e)return ctx.reply('Reference not found.');if(!e.telegram_user_id)return ctx.reply('This request has no Telegram user ID.');await ctx.telegram.sendMessage(e.telegram_user_id,`🏢 Maline Apartments Staff\n\n${message}\n\nReference: ${ref}`);db.prepare("UPDATE enquiries SET status='pending',assigned_to=?,updated_at=CURRENT_TIMESTAMP WHERE reference=?").run(ctx.from.username||ctx.from.first_name,ref);return ctx.reply('✅ Reply sent to the customer.')});
 bot.on('new_chat_members',async ctx=>{const g=getOrCreateGroup(ctx.chat);if(!g.welcome_enabled)return;for(const member of ctx.message.new_chat_members){if(member.is_bot)continue;const tpl=g.welcome_message||'👋 Welcome, {first_name}!\n\nWelcome to {group_name}. 🏢💗\n\n🏠 View apartments\n📅 Schedule a viewing\n🛠 Request assistance\n🌐 Translation: {primary_language} ↔ {secondary_language}\n\nPlease be respectful and avoid spam.';const text=tpl.replaceAll('{first_name}',member.first_name||'there').replaceAll('{last_name}',member.last_name||'').replaceAll('{username}',member.username?`@${member.username}`:'').replaceAll('{group_name}',ctx.chat.title||'Maline Apartments').replaceAll('{primary_language}',g.primary_language).replaceAll('{secondary_language}',g.secondary_language);await ctx.reply(text,Markup.inlineKeyboard([[Markup.button.webApp('🏠 View Apartments',env.webAppUrl)],[Markup.button.callback('📅 Schedule Viewing','customer:viewing')]]));}}
 );
 bot.action('customer:viewing',async ctx=>{await ctx.answerCbQuery();return ctx.reply('Send one message using this format:\n\n#viewing\nName: Your name\nPhone: Your phone\nEmail: Optional\nRoom: Room name\nDate: Preferred date and time\nMessage: Your request')});
 bot.action('customer:message',async ctx=>{await ctx.answerCbQuery();return ctx.reply('Send one message using this format:\n\n#staff\nName: Your name\nPhone: Your phone\nSubject: Your subject\nMessage: Your message')});
 bot.action('customer:languages',async ctx=>{await ctx.answerCbQuery();return ctx.reply('Group admins can select any language codes supported by the connected translation service, for example /setlanguages en zh or /setlanguages km en.')});
 bot.action(/^enquiry:(accepted|pending|declined):(.+)$/,async ctx=>{if(!(await isAdmin(ctx)))return ctx.answerCbQuery('Admins only',{show_alert:true});const [,status,ref]=ctx.match;const e=db.prepare('SELECT * FROM enquiries WHERE reference=?').get(ref);if(!e)return ctx.answerCbQuery('Request not found',{show_alert:true});db.prepare('UPDATE enquiries SET status=?,assigned_to=?,updated_at=CURRENT_TIMESTAMP WHERE reference=?').run(status,ctx.from.username||ctx.from.first_name,ref);if(e.telegram_user_id){const map={accepted:'accepted. Our staff will contact you soon',pending:'received and is pending staff review',declined:'declined. Please contact us for another option'};await ctx.telegram.sendMessage(e.telegram_user_id,`Your Maline Apartments request ${ref} was ${map[status]}.`).catch(()=>{})}await ctx.answerCbQuery(`Status: ${status}`);return ctx.editMessageText(`${ctx.callbackQuery.message.text}\n\n✅ Status: ${status.toUpperCase()}\n👤 Updated by: ${ctx.from.first_name}`)});
 bot.on('text',async (ctx,next)=>{const text=ctx.message.text;if(text.startsWith('/'))return next();if(ctx.chat.type==='private'&&(text.toLowerCase().startsWith('#viewing')||text.toLowerCase().startsWith('#staff'))){const lines={};for(const line of text.split('\n').slice(1)){const i=line.indexOf(':');if(i>0)lines[line.slice(0,i).trim().toLowerCase()]=line.slice(i+1).trim()}const staff=db.prepare("SELECT value FROM app_settings WHERE key='staff_group_id'").get()?.value||env.defaultStaffGroupId;const ref=await createEnquiry(bot,{userId:ctx.from.id,username:ctx.from.username,name:lines.name||ctx.from.first_name,phone:lines.phone,email:lines.email,subject:lines.subject||(text.toLowerCase().startsWith('#viewing')?`Viewing: ${lines.room||'Apartment'}`:'Customer message'),preferredDate:lines.date,message:lines.message||text},staff);return ctx.reply(`✅ Your request was sent to Maline staff.\nReference: ${ref}`)}if(!isGroup(ctx)||ctx.from.is_bot)return;const g=getOrCreateGroup(ctx.chat);if(!g.translation_enabled||text.length>3500)return;try{const detected=await detectLanguage(text);let target;if(detected===g.primary_language)target=g.secondary_language;else if(detected===g.secondary_language)target=g.primary_language;else if(g.other_language_mode==='ignore')return;else target=g.primary_language;const translated=await translateText(text,detected,target);if(!translated||translated.trim().toLowerCase()===text.trim().toLowerCase())return;db.prepare('INSERT INTO translation_logs(chat_id,source_language,target_language) VALUES(?,?,?)').run(String(ctx.chat.id),detected,target);return ctx.reply(`🌐 ${detected} → ${target}\n\n${translated}`,{reply_parameters:{message_id:ctx.message.message_id}})}catch(err){if(err.message.includes('not configured'))return;console.error('Translation error:',err.message)}});
 bot.catch(err=>console.error('Bot error:',err));return bot;
}
module.exports=buildBot;
