require('dotenv').config();
function bool(name, fallback=false){ const v=process.env[name]; return v==null?fallback:['1','true','yes','on'].includes(v.toLowerCase()); }
module.exports={
  nodeEnv:process.env.NODE_ENV||'development',
  port:Number(process.env.PORT||3000),
  appUrl:process.env.APP_URL||`http://localhost:${process.env.PORT||3000}`,
  webAppUrl:process.env.TELEGRAM_WEB_APP_URL||process.env.APP_URL||`http://localhost:${process.env.PORT||3000}`,
  botToken:process.env.TELEGRAM_BOT_TOKEN||'',
  defaultStaffGroupId:process.env.DEFAULT_STAFF_GROUP_ID||'',
  translationApiUrl:(process.env.TRANSLATION_API_URL||'').replace(/\/$/,''),
  translationApiKey:process.env.TRANSLATION_API_KEY||'',
  adminEmail:process.env.ADMIN_EMAIL||'admin@maline.local',
  adminPassword:process.env.ADMIN_PASSWORD||'ChangeMe123!',
  sessionSecret:process.env.SESSION_SECRET||'change-me',
  defaultPrimaryLanguage:process.env.DEFAULT_PRIMARY_LANGUAGE||'en',
  defaultSecondaryLanguage:process.env.DEFAULT_SECONDARY_LANGUAGE||'zh',
  welcomeEnabled:bool('WELCOME_ENABLED',true),
  translationEnabled:bool('TRANSLATION_ENABLED',true)
};
