const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();
const state={rooms:[],current:null,userKey:String(tg?.initDataUnsafe?.user?.id||localStorage.getItem('maline-user')||crypto.randomUUID())};localStorage.setItem('maline-user',state.userKey);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function show(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));scrollTo(0,0);if(id==='favorites')loadFavorites()}
function placeholder(r){return r.photos?.[0]?`<img src="${r.photos[0]}" alt="${r.title}" style="width:100%;height:160px;object-fit:cover">`:'<div class="placeholder">M</div>'}
function card(r){return `<article class="room-card">${placeholder(r)}<div class="body"><small>${r.available?'AVAILABLE':'OCCUPIED'}</small><h3>${r.title}</h3><div class="price">$${Number(r.monthly_price).toLocaleString()} <small>/month</small></div><div class="meta"><span>🛏 ${r.bedrooms||'Studio'}</span><span>🛁 ${r.bathrooms}</span><span>↔ ${r.size_sqm} sqm</span></div><div class="card-actions"><button onclick="openRoom(${r.id})">View details</button><button class="secondary" onclick="saveFavorite(${r.id})">♡</button></div></div></article>`}
async function api(url,opt){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
async function load(){state.rooms=await api('/api/rooms');renderRooms(state.rooms);$('#featured').innerHTML=state.rooms.filter(r=>r.featured).slice(0,4).map(card).join('')||'<p>No featured rooms.</p>';$('#enquiryRoom').innerHTML='<option value="">General enquiry</option>'+state.rooms.map(r=>`<option value="${r.id}">${r.title}</option>`).join('');const s=await api('/api/stats');$('#stats').innerHTML=`<div class="stat"><b>${s.rooms}</b>Rooms</div><div class="stat"><b>${s.available}</b>Available</div><div class="stat"><b>24/7</b>Support</div>`}
function renderRooms(list){$('#roomList').innerHTML=list.map(card).join('')||'<p>No matching apartment found.</p>'}
window.openRoom=id=>{const r=state.rooms.find(x=>x.id===id);state.current=r;$('#roomDetail').innerHTML=`${r.photos?.[0]?`<img src="${r.photos[0]}" class="detail-placeholder" style="width:100%;object-fit:cover">`:'<div class="detail-placeholder">M</div>'}<small>${r.available?'AVAILABLE NOW':'CURRENTLY OCCUPIED'}</small><h2>${r.title}</h2><div class="price">$${Number(r.monthly_price).toLocaleString()} / month</div><p>${r.description||''}</p><div class="detail-grid"><div class="detail-box">🛏 Bedrooms<br><b>${r.bedrooms||'Studio'}</b></div><div class="detail-box">🛁 Bathrooms<br><b>${r.bathrooms}</b></div><div class="detail-box">↔ Size<br><b>${r.size_sqm} sqm</b></div><div class="detail-box">⌂ Floor<br><b>${r.floor||'Ask staff'}</b></div></div><h3>Facilities</h3><ul class="list">${r.facilities.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Services included</h3><ul class="list">${r.servicesIncluded.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Services excluded</h3><ul class="list">${r.servicesExcluded.map(x=>`<li>${x}</li>`).join('')}</ul><div class="book-box"><h3>Request this apartment</h3><form id="bookForm"><input name="customerName" placeholder="Full name" required><input name="phone" placeholder="Phone" required><input name="email" type="email" placeholder="Email"><input name="moveInDate" type="date" required><textarea name="specialRequest" placeholder="Special request"></textarea><button>Submit booking request</button><p id="bookResult"></p></form></div>`;show('detail');$('#bookForm').onsubmit=book}
window.saveFavorite=async id=>{await api('/api/favorites',{method:'POST',body:JSON.stringify({userKey:state.userKey,roomId:id})});toast('Saved to favorites')}
async function loadFavorites(){const list=await api('/api/favorites/'+encodeURIComponent(state.userKey));$('#favoriteList').innerHTML=list.map(card).join('')||'<p>You have no saved apartments yet.</p>'}
async function book(e){e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.roomId=state.current.id;b.telegramUserId=tg?.initDataUnsafe?.user?.id||'';try{const x=await api('/api/bookings',{method:'POST',body:JSON.stringify(b)});$('#bookResult').textContent=`Request sent. Reference: ${x.reference}`;e.target.reset()}catch(err){$('#bookResult').textContent=err.message}}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');$('#searchBtn').onclick=()=>{const q=$('#searchInput').value.toLowerCase();renderRooms(state.rooms.filter(r=>(r.title+' '+r.description+' '+r.facilities.join(' ')).toLowerCase().includes(q)));show('rooms')};$('#bedFilter').onchange=$('#availableFilter').onchange=()=>{let x=state.rooms;if($('#bedFilter').value!=='')x=x.filter(r=>r.bedrooms===Number($('#bedFilter').value));if($('#availableFilter').checked)x=x.filter(r=>r.available);renderRooms(x)};
$('#enquiryForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.telegramUserId=tg?.initDataUnsafe?.user?.id||'';b.telegramUsername=tg?.initDataUnsafe?.user?.username||'';try{const x=await api('/api/enquiries',{method:'POST',body:JSON.stringify(b)});$('#enquiryResult').textContent=`Sent successfully. Reference: ${x.reference}`;e.target.reset()}catch(err){$('#enquiryResult').textContent=err.message}};
$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#chatInput'),msg=input.value.trim();if(!msg)return;$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble user">${msg.replaceAll('<','&lt;')}</div>`);input.value='';const x=await api('/api/assistant',{method:'POST',body:JSON.stringify({message:msg})});$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble bot">${x.answer}</div>`);$('#chat').scrollTop=$('#chat').scrollHeight};
setTimeout(()=>{$('#splash').classList.add('hidden');$('#app').classList.remove('hidden')},700);load().catch(e=>toast(e.message));
