const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
let rooms=[];
const $=s=>document.querySelector(s);
async function loadRooms(){const res=await fetch('/api/rooms');rooms=await res.json();render();}
function render(){const q=$('#search').value.toLowerCase(),beds=$('#bedrooms').value;const filtered=rooms.filter(r=>(!q||`${r.title} ${r.bedrooms} ${r.size_sqm}`.toLowerCase().includes(q))&&(!beds||String(r.bedrooms)===beds));$('#count').textContent=`${filtered.length} room${filtered.length===1?'':'s'}`;$('#rooms').innerHTML=filtered.map(r=>`<article class="room"><div class="placeholder">M</div><div class="room-body"><h3>${esc(r.title)}</h3><div class="meta"><span>🛏 ${r.bedrooms||'Studio'}</span><span>🛁 ${r.bathrooms}</span><span>↔ ${r.size_sqm} sqm</span><span>🏢 ${esc(r.floor||'Ask staff')}</span></div><div class="price">$${Number(r.monthly_price).toLocaleString()} <small>/ month</small></div><div class="room-actions"><button onclick="detail(${r.id})">View details</button><button class="save" onclick="save(${r.id})">♡</button></div></div></article>`).join('')||'<div class="loading">No matching apartments.</div>'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function detail(id){const r=rooms.find(x=>x.id===id);$('#modalBody').innerHTML=`<small>ROOM DETAILS</small><h2>${esc(r.title)}</h2><div class="placeholder">M</div><p>${esc(r.description)}</p><div class="detail-list"><div>🛏 Bedrooms: ${r.bedrooms||'Studio'}</div><div>🛁 Bathrooms: ${r.bathrooms}</div><div>📐 Size: ${r.size_sqm} sqm</div><div>🏢 Floor: ${esc(r.floor)}</div><div>💵 Price: $${Number(r.monthly_price).toLocaleString()} / month</div></div><h3>Facilities</h3><div class="chips">${r.facilities.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h3>Services included</h3><div class="detail-list">${r.servicesIncluded.map(x=>`<div>✓ ${esc(x)}</div>`).join('')}</div><h3>Services excluded</h3><div class="detail-list">${r.servicesExcluded.map(x=>`<div>• ${esc(x)}</div>`).join('')}</div><button style="width:100%;padding:15px;border:0;border-radius:14px;background:var(--pink);color:white;font-weight:800" onclick="contact('${esc(r.title)}')">Schedule viewing</button>`;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function save(id){const saved=JSON.parse(localStorage.getItem('maline-favorites')||'[]');const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('maline-favorites',JSON.stringify(next));tg?.HapticFeedback?.impactOccurred('light');alert(next.includes(id)?'Saved to favorites':'Removed from favorites')}
function contact(room='Apartment'){const username='';const msg=encodeURIComponent(`#viewing\nName: ${tg?.initDataUnsafe?.user?.first_name||''}\nPhone: \nRoom: ${room}\nDate: \nMessage: I would like to schedule a viewing.`);if(username)location.href=`https://t.me/${username}?text=${msg}`;else{tg?.close();alert('Open the Maline bot and send a #viewing request. Add your bot username in mini-app/js/app.js after BotFather setup.')}}
$('#search').addEventListener('input',render);$('#bedrooms').addEventListener('change',render);$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');$('#contactBtn').onclick=()=>contact();$('#staffNav').onclick=()=>contact();$('#languageBtn').onclick=()=>alert('Group administrators can select two languages with /setlanguages en zh');loadRooms().catch(()=>$('#rooms').innerHTML='<div class="loading">Unable to load apartments.</div>');
